#pragma kernel TestSampleBuffer
#pragma kernel TestGetDerivativeU
#pragma kernel TestGetDerivativeV

float _Offset;
bool _Smooth;
float _AccelerateStart;

#include "../../Materials/AudioSampleToPosition.hlsl"

RWStructuredBuffer<float> _Result;
float4 _UvIndex;


float _Set[5];

[numthreads(1,1,1)]
void TestSampleBuffer (uint3 id : SV_DispatchThreadID)
{
    _Result[0] = SampleBuffer(_UvIndex.xy);
}
