#pragma kernel SpectrumVisualizer

RWStructuredBuffer<float> _Spectrogram;
RWStructuredBuffer<float> _PrevSpectrogram;

int _IndexOffset;
uint _Resolution;
uint _Depth;

[numthreads(8, 8, 1)]
void SpectrumVisualizer (uint3 id: SV_DispatchThreadID)
{

	int clampedIndex = clamp( id.y + _IndexOffset, id.y, _Depth);
	_Spectrogram[id.x + id.y * _Resolution] = _PrevSpectrogram[id.x +  clampedIndex * _Resolution];	

}

