#pragma kernel SpectrumVisualizer

RWStructuredBuffer<float> _Positions;
RWStructuredBuffer<float> _PrevPositions;

int _IndexOffset;
uint _Resolution;
uint _Depth;

[numthreads(8, 8, 1)]
void SpectrumVisualizer (uint3 id: SV_DispatchThreadID)
{

	int clampedIndex = clamp( id.y + _IndexOffset, id.y, _Depth);
	_Positions[id.x + id.y * _Resolution] = _PrevPositions[id.x +  clampedIndex * _Resolution];	

}

