#pragma kernel TestShaderMain

RWTexture2D<float> _Spectrogram;
RWTexture2D<float> _PrevSpectrogram;

[numthreads(8,8,1)]
void TestShaderMain (uint3 id : SV_DispatchThreadID)
{    
    // _Spectrogram[id.xy] = float4(id.x & id.y, (id.x & 15)/15.0, (id.y & 15)/15.0, 0.0);
    // _PrevSpectrogram[id.xy] = float4(id.x & id.y, (id.x & 15)/15.0, (id.y & 15)/15.0, 0.0);

    _Spectrogram[id.xy] = float((id.x & 15)/15.0);
	_PrevSpectrogram[id.xy] = float((id.x & 15)/15.0);
}
